name: Rust CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install ALSA
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Build project
        run: cargo build --release

      - name: Check code style (fmt)
        run: cargo fmt --all

      - name: Check warnings (clippy)
        run: cargo clippy -- -D warnings
        continue-on-error: true
